force-app/main/default/objects/Portfolio_Contact__c/Portfolio_Contact__c.object-meta.xml
<CustomObject>
    <label>Portfolio Contact</label>
    <nameField>
        <displayFormat>CT-{0000000000}</displayFormat>
        <label>Portfolio Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Portfolio Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Portfolio_Contact__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Portfolio_Contact__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Read</fullName>
            </value>
            <value>
                <fullName>Answered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Portfolio_Profile__c/Portfolio_Profile__c.object-meta.xml
<CustomObject>
    <label>Portfolio Profile</label>
    <nameField>
        <label>Portfolio Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolio Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/domains/PortfolioContactDomain.cls
public without sharing  class PortfolioContactDomain {
    public static Portfolio_Contact__c createContact(PortfolioContactDTO contactDTO) {
        Portfolio_Contact__c contactRecord = new Portfolio_Contact__c();
        contactRecord.Contact_Name__c = contactDTO.name;
        contactRecord.Email__c = contactDTO.email;
        contactRecord.Message__c = contactDTO.message;
        contactRecord.Status__c = 'New';
        contactRecord.Portfolio_Profile__c = contactDTO.profileId;
        return contactRecord;
    }
}