force-app/main/default/objects/Portfolio_Profile__c/Portfolio_Profile__c.object-meta.xml
<CustomObject>
    <label>Portfolio Profile</label>
    <nameField>
        <label>Portfolio Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolio Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Portfolio_Profile__c/fields/Bio__c.field-meta.xml
<CustomField>
    <fullName>Bio__c</fullName>
    <label>Bio</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Portfolio_Profile__c/fields/Github_URL__c.field-meta.xml
<CustomField>
    <fullName>Github_URL__c</fullName>
    <label>Github URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Portfolio_Profile__c/fields/Linkedin_URL__c.field-meta.xml
<CustomField>
    <fullName>Linkedin_URL__c</fullName>
    <label>Linkedin URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Portfolio_Profile__c/fields/Profile_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Profile_Image_URL__c</fullName>
    <label>Profile Image URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Portfolio_Profile__c/fields/Whatsapp_Phone__c.field-meta.xml
<CustomField>
    <fullName>Whatsapp_Phone__c</fullName>
    <label>Whatsapp Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Portfolio_Profile__c/fields/Years_Experience__c.field-meta.xml
<CustomField>
    <fullName>Years_Experience__c</fullName>
    <formula>( TODAY() - Career_Start_Date__c) / 365</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Years Experience</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/selectors/PortfolioProfileSelector.cls
public with sharing class PortfolioProfileSelector {
    public static Portfolio_Profile__c getPortfolioProfile(String Id) {
        Portfolio_Profile__c profile = [
            SELECT Name, Title__c, Bio__c, Profile_Image_Url__c, LinkedIn_Url__c, Github_Url__c, Email__c, Phone__c, Whatsapp_Phone__c, Years_Experience__c
            FROM Portfolio_Profile__c
            WHERE Id = :Id
            LIMIT 1
        ];
        return profile;
    }
}