force-app/main/default/objects/Portfolio_Profile__c/Portfolio_Profile__c.object-meta.xml
<CustomObject>
    <label>Portfolio Profile</label>
    <nameField>
        <label>Portfolio Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolio Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Portfolio_Profile__c/fields/Bio__c.field-meta.xml
<CustomField>
    <fullName>Bio__c</fullName>
    <label>Bio</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Portfolio_Profile__c/fields/Github_URL__c.field-meta.xml
<CustomField>
    <fullName>Github_URL__c</fullName>
    <label>Github URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Portfolio_Profile__c/fields/Linkedin_URL__c.field-meta.xml
<CustomField>
    <fullName>Linkedin_URL__c</fullName>
    <label>Linkedin URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Portfolio_Profile__c/fields/Profile_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Profile_Image_URL__c</fullName>
    <label>Profile Image URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Portfolio_Profile__c/fields/Trailhead_URL__c.field-meta.xml
<CustomField>
    <fullName>Trailhead_URL__c</fullName>
    <label>Trailhead URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Portfolio_Profile__c/fields/Whatsapp_Phone__c.field-meta.xml
<CustomField>
    <fullName>Whatsapp_Phone__c</fullName>
    <label>Whatsapp Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Portfolio_Profile__c/fields/Years_Experience__c.field-meta.xml
<CustomField>
    <fullName>Years_Experience__c</fullName>
    <formula>( TODAY() - Career_Start_Date__c) / 365</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Years Experience</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Portfolio_Skill__c/Portfolio_Skill__c.object-meta.xml
<CustomObject>
    <label>Portfolio Skill</label>
    <nameField>
        <label>PortfolioSkill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolio Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Portfolio_Skill__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Frontend</fullName>
            </value>
            <value>
                <fullName>Backend</fullName>
            </value>
            <value>
                <fullName>DevOps</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Language</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Portfolio_Skill__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beginner</fullName>
            </value>
            <value>
                <fullName>Intermediate</fullName>
            </value>
            <value>
                <fullName>Upper Intermediate</fullName>
            </value>
            <value>
                <fullName>Advanced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Portfolio_Skill__c/fields/Portfolio_Profile__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_Profile__c</fullName>
    <label>Portfolio Profile</label>
    <referenceTo>Portfolio_Profile__c</referenceTo>
    <relationshipLabel>Portfolio Skills</relationshipLabel>
    <relationshipName>Portfolio_Skills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/domains/PortfolioProfileDomain.cls
public without sharing class PortfolioProfileDomain {
    public static PortfolioProfileDTO toDTO(Portfolio_Profile__c record) {
        if (record == null) return null;

        List<PortfolioProfileDTO.PortfolioSkillDTO> skillDTOList = new List<PortfolioProfileDTO.PortfolioSkillDTO>();

        if (record.Portfolio_Skills__r != null) {
            for (Portfolio_Skill__c skill : record.Portfolio_Skills__r) {
                skillDTOList.add(new PortfolioProfileDTO.PortfolioSkillDTO(
                    skill.Name,
                    skill.Category__c,
                    skill.Level__c,
                    (skill.Display_Order__c == null ? null : Integer.valueOf(skill.Display_Order__c))
                ));
            }
        }
        return new PortfolioProfileDTO(
            record.Name,
            record.Title__c,
            record.Bio__c,
            record.Profile_Image_Url__c,
            record.LinkedIn_Url__c,
            record.Github_Url__c,
            record.Trailhead_URL__c,
            record.Email__c,
            record.Phone__c,
            record.Whatsapp_Phone__c,
            (record.Years_Experience__c == null ? null : Double.valueOf(record.Years_Experience__c)),
            skillDTOList
        );
    }
}